WIFI_SSID = "RescueNet-5G"
WIFI_PASSWORD = "changeme123"

DEVICE_ID = "master_probe_01"
DEVICE_NAME = "Master Probe - Sector 1"
FIRMWARE_VERSION = "1.0.0"

HTTP_PORT = 80
API_PREFIX = "/api/v1"

OLED_ENABLED = True
SERIAL_BAUD = 115200

DEFAULT_SECTOR_DWELL_MS = 3000
DEFAULT_SCAN_DURATION_SECONDS = 300
DEFAULT_CALIBRATION_DURATION_SECONDS = 60
